### ISSUE TITLE
Gentoo qutim-9999 build problem with qutim-developers-k8json repo

### ISSUE THREAD

**Issue by bober2000** [euroelessar/qutim#339]
Getting message:
Clone of 'git://gitorious.org/+qutim-developers/k8jsonqt/qutim-developers-k8json.git' into submodule path 'core/3rdparty/k8json' failed
So qutim is not building

**Comment by KsenZ** [comment]
In .gitmodules replace url for k8json
url =http://git.gitorious.org/k8jsonqt/qutim-developers-k8json.git

**Comment by bober2000** [comment]
It's ok now but another problem - build crash on compiling jsonhistory - where I have to post bugs on Gentoo build and what info do you need?

**Comment by euroelessar** [comment]
How does exactly build fail? May you provide any build log?

**Comment by bober2000** [comment]
Here is my build.log https://www.dropbox.com/s/7fpwu1wjga5wwsg/build.log?dl=0
And emerge --info https://www.dropbox.com/s/dyirlaol2v72t7j/info.txt?dl=0
Feel free to ask for any other needed info

**Comment by euroelessar** [comment]
Does Gentoo clone git repos by using `git submodule update --init --recursive` or by using `git pull` to each submodule?

Looks like it's the second and you've replaced url for q-xdg by my clone at GitHub, it contains fixes for Qt5 support, but I didn't check them for Qt4 at all. Is it possible to use `git submodule update --init --recursive` during checkout?

**Comment by bober2000** [comment]
As I can see its make full clone of repo:
git-2_initial_clone: git clone  "git://github.com/euroelessar/qutim.git" "/usr/portage/distfiles/egit-src/qutim"
git-2_initial_clone: EGIT_REPO_URI_SELECTED="git://github.com/euroelessar/qutim.git"

**Comment by euroelessar** [comment]
The question is about 'how does it do a full clone'? qutIM's repo has several submodules and it's critical to initialize them correctly. May I have a look at your ebuild?

@VladRassokhin  may you have a look at this as well?

**Comment by bober2000** [comment]
I'm using ebuild from qutim gentoo-portage-overlay
https://github.com/qutIM/gentoo-portage-overlay/blob/master/net-im/qutim/qutim-9999.ebuild
gentoo.ru chat says that we can try to use git-r3 in ebuild but  I didn't tried that

**Comment by euroelessar** [comment]
I've made some changes to Q-Xdg repo, may you check again?

**Comment by bober2000** [comment]
No luck again https://www.dropbox.com/s/7fpwu1wjga5wwsg/build.log?dl=0

**Comment by bober2000** [comment]
Switched off ccache - got another trouble https://www.dropbox.com/s/l17mmyb99m094rz/build.2.log?dl=0

**Comment by euroelessar** [comment]
May you clean qutim's git cache? Looks like it doesn't update submodules at all

**Comment by bober2000** [comment]
How do I do that? I have deleted qutim repo from layman and re-added it again, also I remove /usr/portage/distfiles/egit-src/qutim before trying to rebuild

**Comment by euroelessar** [comment]
May you show me the output of the following commands at `/usr/portage/distfiles/egit-src/qutim`?
 * `git submodule status`
 * `git status`

**Comment by bober2000** [comment]
bobers-comp qutim # git submodule status
 2910de9e65ddaee181009bb2d81fa330e225c9ea artwork (remotes/origin/refactoring-139-g2910de9)
 567f28e7bf76305153a61170fafafdd0db3487cb core/3rdparty/k8json (heads/master)
 5ccb82156d650b6db7bfbe1ad41eb1aa537b5e8c core/3rdparty/q-xdg (5ccb821)
 38913b901e94095ca510f1f47038414f451d3974 plugins/docktile/qtdocktile (1.0beta-52-g38913b9)
 08734edd712ee90f070f7950a4c728b83f135211 protocols/jabber/jreen (v1.1.0-77-g08734ed)
 f96eafdbfa384752a0868e0a2100a598ab3d9120 protocols/vkontakte/vreen (remotes/origin/dev-30-gf96eafd)
 d6f33175d4ef9ff3948cb5ebfd431356af8f3bc4 qbs (d6f3317)
 0826b463d725037130f7410a440e32deb61df092 qml/imports/Controls (remotes/origin/example-46-g0826b46)
 2e9c16c6740b43d86322a8c621146f7679eafb53 translations (2e9c16c)
bobers-comp qutim # git status
On branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working directory clean
bobers-comp qutim #

**Comment by euroelessar** [comment]
May you try again? I've done manual submodules update

**Comment by bober2000** [comment]
No again https://www.dropbox.com/s/7fpwu1wjga5wwsg/build.log?dl=0

**Comment by euroelessar** [comment]
BTW, did you remove a patch for replacing submodule urls?

**Comment by bober2000** [comment]
If you about
"In .gitmodules replace url for k8json
url =http://git.gitorious.org/k8jsonqt/qutim-developers-k8json.git"
than yes - I'm using clean repo

**Comment by bober2000** [comment]
Any updates?

**Comment by bober2000** [comment]
Dying on
/var/tmp/portage/net-im/qutim-9999/work/qutim-9999/core/libqutim/declarativeview.cpp:29:28: fatal error: QDeclarativeItem: No such file or directory
 #include <QDeclarativeItem>
Build log https://www.dropbox.com/s/h5ig9f0trz2ontf/build4.log?dl=0

**Comment by euroelessar** [comment]
Do you have installed qt-declarative library?

**Comment by bober2000** [comment]
No, I've installed it but again get same message:
eix dev-qt/qtdeclarative
[I] dev-qt/qtdeclarative 5.4.1
Build log https://www.dropbox.com/s/7fpwu1wjga5wwsg/build.log?dl=0

**Comment by euroelessar** [comment]
As I understand you need Qt4 version of this package, not Qt5 (may it's called as QtQuick, I'm not sure)

**Comment by bober2000** [comment]
The problem was with skype that installed qt5 libs, but we need to add dev-qt/qtdeclarative in to dependency in ebuild to prevent this in future

**Comment by euroelessar** [comment]
I believe that in the nearest future ebuild will be upgraded to build qutim with Qt5

**Comment by bober2000** [comment]
Trying to build live version again. Getting:
-- Configuring done
CMake Error at libqutim/CMakeLists.txt:124 (ADD_LIBRARY):
  Cannot find source file:

    /var/tmp/portage/net-im/qutim-9999/work/qutim-9999/core/3rdparty/k8json/k8json.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx


CMake Error: CMake can not determine linker language for target: libqutim
CMake Error: Cannot determine link language for target "libqutim".

Build log https://www.dropbox.com/s/7fpwu1wjga5wwsg/build.log?dl=0
Enviroment log https://www.dropbox.com/s/yvabmse8udbsbup/environment?dl=0

On previous version 0.3.2 - I have not tray icon

**Comment by Fat-Zer** [comment]
Are there any reasons you don't build the version 0.3.2 or 0.3.3 from the main portage tree? If you have no tray icon on this version, could you post some common information like *emerge --info net-im/qutim*; are where any messages when you run from the command prompt? what if you increase verbosity/turn on the debug mode (not sure how to do it for qutim)? what DE you use?
Also feel free to fill in a gentoo bug report in that case...

The overlay seems to be unmaintained for quite a while, I suppose it could be particulary broken by now...
