### ISSUE TITLE
XMPP: qutim misinterprets MUC messages containing <thread> node as private

### ISSUE THREAD

**Issue by l29ah** [euroelessar/qutim#403]
Causing them to appear in the private messages and produce annoyingly unrelated notifications.

**Comment by nico-izo** [comment]
Could you please give an example of XML entity that was incorrectly interpreted?Perhaps, from what client/version it was sent.What version of qutIM and Jreen are you running?Jreen is the jabber library we are using. 02.11.2018, 05:13, "Sergey Alirzaev" <notifications@github.com>:Causing them to appear in the private messages and produce annoyingly unrelated notifications.

**Comment by l29ah** [comment]
Never mind, i cannot reproduce it on the latest version.
